version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            gradle test
            gradle jar
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: /code/test-results
          destination: prefix
      - store_artifacts:
          path: build/libs
          destination: prefix
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'hi man'
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            gradle jar
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo 'hi man'
      - store_artifacts:
          path: build/libs
          destination: prefix

workflows:
  version: 2
  two_job_flow:
    jobs:
      - test
      - package
          requires:
              - test
