jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            gradle test
            gradle jar
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: /code/test-results
          destination: prefix
      - store_artifacts:
          path: build/libs
          destination: prefix
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'hi man'
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            gradle jar
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo 'hi man'
      - store_artifacts:
          path: build/libs
          destination: prefix

  dockerize:
    machine: true
    steps:
      - checkout
     # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
      - run: docker build -t $DOCKER_USER/myfirstapp:$CIRCLE_SHA1 .

     # deploy the image
      - run: docker push $DOCKER_USER/myfirstapp:$CIRCLE_SHA1

workflows:
  version: 2
  two_job_flow:
    jobs:
      - test
      - package:
          requires:
            - test   
      -dockerize:
          requires:
            - test
