version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            gradle test
            gradle jar
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo 'hi man'
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: /code/test-results
          destination: prefix
      - store_artifacts:
          path: build/libs
          destination: prefix
